version: '3.7'
services:
  redis:
    image: redis:3.0.7
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - parserdb:/data/db
    ports:
      - 27017:27017
  parser:
    container_name: parser
    build:
      context: ./
    depends_on:
      - redis
      - mongo
    environment:
      APP_REDIS_HOST: redis
      APP_REDIS_PORT: 6379
      MONGO_USER: root
      MONGO_PASSWORD: password
      BRAIN_LOGIN: admin
      BRAIN_PASSWORD: password
    ports:
      - 3000:3000
    volumes:
      - ./:/parser
      #- /parser/node_modules
    command: |
      wait-for redis:6379 -t 260 --
      npm start
volumes:
  parserdb:
    driver: local
  redis_data:
    driver: local